TokTok/qTox

- .travis.yml
- .travis/deploy-install
- .travis/git-deploy
- .travis/linux-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/2)
> Move apt packages to the travis config.

- src/core/toxencrypt.cpp
- src/persistence/db/rawdatabase.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/4)
> Update qtox to new immutable toxencryptsave api.

- src/core/coreav.cpp
- src/core/coreav.h
Introduced in https://github.com/TokTok/c-toxcore/pull/578.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/5)
> Update to split bit_rate_set functions.

- src/core/core.cpp
- src/core/core.h
- src/core/coreav.cpp
- src/core/coreav.h
- src/nexus.cpp
- src/widget/widget.cpp
- src/widget/widget.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/12)
> Adopt new conference peer nick/list_changed callbacks.

- src/widget/widget.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/15)
> avoid crash on ubuntu 16.04

- BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/17)
> WIP: Add support for building on Windows using Bazel.

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/27)
> Add qtmultimedia dependency.

- .github/settings.yml
- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/29)
> Disable issues on toktok/qtox.

- BUILD.bazel
- audio/BUILD.bazel
- osx/BUILD.bazel
- src/BUILD.bazel
- test/BUILD.bazel
- util/BUILD.bazel
- windows/BUILD.bazel
It's default now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/34)
> chore: layering check on qtox.

- .github/settings.yml
Centralised settings means we can update them without having to pass all the CI checks of each repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/38)
> chore: Remove settings.yml in favour of hs-github-tools.

- .github/actions/build-docker-image/action.yml
- .github/actions/load-docker-image/action.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/39)
> chore: Update github actions.

- .restyled.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/43)
> chore: Disable restyled for now

- .cirrus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/44)
> chore(ci): Lower cirrus ci timeout

- .cirrus.yml
- .github/workflows/ci.yml
- .github/workflows/docker.yml
- buildscripts/docker/Dockerfile.alpine
- cmake/Dependencies.cmake
- src/appmanager.cpp
- src/net/updatecheck.cpp
- src/widget/form/settings/aboutform.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/46)
> chore: Add alpine docker build to CI.

- util/src/toxcoreerrorparser.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/41)
> chore: Add new error enumerator for conference join.

- res/io.github.qtox.qTox.appdata.xml
Needed for flathub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/48)
> chore: add developer to appstream metainfo

- audio/src/backend/openal.cpp
- src/model/about/aboutfriend.cpp
- src/model/notificationgenerator.cpp
- src/model/sessionchatlog.cpp
- src/net/avatarbroadcaster.cpp
- src/nexus.cpp
- src/persistence/paths.cpp
- src/persistence/settings.cpp
- src/persistence/settingsserializer.cpp
- src/video/cameradevice.cpp
- src/video/camerasource.cpp
- src/widget/about/aboutfriendform.cpp
- src/widget/form/chatform.cpp
- src/widget/form/genericchatform.cpp
- src/widget/form/groupinvitewidget.cpp
- src/widget/form/profileform.cpp
- src/widget/form/settings/aboutform.cpp
- src/widget/friendlistwidget.cpp
- src/widget/friendwidget.cpp
- src/widget/passwordedit.cpp
- src/widget/tool/movablewidget.cpp
- src/widget/translator.cpp
- src/widget/widget.cpp
- test/chatlog/chatlinestorage_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/52)
> cleanup: Fix a few more deprecation warnings.

- .restyled.yaml
- src/platform/camera/avfoundation.h
- src/platform/camera/avfoundation.mm
- src/platform/timer_osx.cpp
- src/video/cameradevice.cpp
- src/video/videoframe.cpp
- src/widget/contentdialog.cpp
- src/widget/flowlayout.h
- src/widget/loginscreen.cpp
- src/widget/loginscreen.h
- src/widget/tool/messageboxmanager.cpp
- src/widget/tool/screengrabberchooserrectitem.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/53)
> cleanup: More deprecation fixes.

- .restyled.yaml
- src/platform/camera/avfoundation.h
- src/platform/timer_osx.cpp
- src/video/cameradevice.cpp
- src/video/videoframe.cpp
- src/widget/contentdialog.cpp
- src/widget/flowlayout.h
- src/widget/loginscreen.cpp
- src/widget/loginscreen.h
- src/widget/tool/messageboxmanager.cpp
- src/widget/tool/screengrabberchooserrectitem.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/54)
> chore: Enable restyled code formatter.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/57)
> chore: Reduce the amount of CI builds we do.

- .github/workflows/build-test-deploy.yaml
- docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/59)
> chore: Add back the 32 bit windows build.

- src/appmanager.cpp
- src/chatlog/chatwidget.cpp
- src/model/sessionchatlog.cpp
- src/persistence/history.cpp
- src/widget/contentdialog.cpp
- src/widget/emoticonswidget.cpp
- src/widget/form/genericchatform.cpp
- src/widget/form/loadhistorydialog.cpp
- src/widget/form/searchsettingsform.cpp
- src/widget/genericchatitemlayout.h
- src/widget/tool/activatedialog.h
- src/widget/tool/croppinglabel.cpp
- src/widget/widget.cpp
We're definitely greater than any qt5 version at this point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/62)
> cleanup: Delete all qt5 version checks.

- osx/macfixrpath
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/64)
> chore: Fix macos deploy build rpath corrector.

- .github/workflows/build-test-deploy.yaml
This makes them easily accessible as part of our upcoming release. It's very much not ready for prime time, but curious users can try it out and maybe contribute improvements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/65)
> chore: Upload apks to the release and nightly tags.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/68)
> chore: Fix apk path so release uploads actually work.

- src/chatlog/chatwidget.cpp
- src/core/corefile.h
- src/model/chatroom/friendchatroom.cpp
- src/model/friend.h
- src/model/ichatlog.h
- src/model/imessagedispatcher.h
- src/persistence/history.cpp
- src/persistence/offlinemsgengine.h
- src/persistence/profile.h
- src/widget/categorywidget.h
- src/widget/form/chatform.h
- src/widget/form/filesform.cpp
- src/widget/form/filesform.h
- src/widget/friendlistlayout.h
- src/widget/friendlistwidget.cpp
- src/widget/friendlistwidget.h
- src/widget/widget.h
- test/model/friendmessagedispatcher_test.cpp
- test/model/groupmessagedispatcher_test.cpp
- test/widget/filesform_test.cpp
And transitively on tox.h. This reduces the amount of rebuild that needs to happen when we change tox.h.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/70)
> cleanup: Minimise direct dependencies on core.h.

- .github/workflows/build-test-deploy.yaml
- docker-compose.yml
Instead of building it in CI here, it's built in the dockerfiles CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/101)
> chore: Use built docker image from docker hub.

- .ci-scripts/build-osx-deps.sh
- .github/workflows/build-test-deploy.yaml
These take 20 minutes to build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/103)
> chore: Cache built macos dependencies in CI.

- src/appmanager.cpp
Currently, any logging happening in audio/ or util/ contains the full path, i.e. also the user's $HOME, i.e. probably the user's local username, which they might not want to disclose.
Also, when data saves happen, they always show the full path.
This change tries harder to hide user info by replacing the user's home path in log messages with "~" and fixes the audio/ and util/ leakage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/94)
> fix(security): Do a better job of anonymising the log output.

- cmake/Testing.cmake
- src/widget/form/settings/generalform.cpp
- src/widget/form/settings/generalform.h
- test/BUILD.bazel
- test/widget/form/settings/generalform_test.cpp
- tools/update-translation-files.sh
- translations/CMakeLists.txt
- translations/translations.qrc
These already existed, but weren't available in the UI.
Also add test to make sure all translations are available in the UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/114)
> feat: Add new translations: Bengali, Latvian, Flemish, Vietnamese.

- src/BUILD.bazel
- src/chatlog/content/filetransferwidget.ui
- src/core/toxcall.h
- src/mainwindow.ui
- src/model/status.cpp
- src/widget/form/profileform.ui
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/72)
> cleanup: Don't use `<header.h>` for local includes.

- src/widget/form/settings/avform.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/121)
> fix: remove extra newline in log

- .restyled.yaml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/123)
> docs: Update readme to say we're active on qTox again.

- .ci-scripts/build-qtox-linux.sh
- .github/workflows/build-test-deploy.yaml
- .restyled.yaml
- android/cross-compile/build.sh
- docker-compose.yml
- flatpak/build.sh
We only do a single one, but it's more informative in the CI job view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/127)
> chore: Add arch and build type to Android matrix.

- src/persistence/history.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/125)
> style: Reformat SQL query code a bit to reduce right-alignment.

- src/widget/form/settings/generalform.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/130)
> fix: Add Caucasian Albanian Script writing system mapping.

- .restyled.yaml
- CMakeLists.txt
- audio/CMakeLists.txt
- cmake/CheckAtomic.cmake
- cmake/Dependencies.cmake
- cmake/Installation.cmake
- cmake/Testing.cmake
- cmake/warnings/CMakeLists.txt
- test/dbutility/CMakeLists.txt
- test/mock/CMakeLists.txt
- translations/CMakeLists.txt
- util/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/132)
> cleanup: Reformat all the cmake files with cmake-format.

- CMakeLists.txt
- INSTALL.md
- src/platform/desktop_notifications/desktopnotify.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/135)
> fix: Fix use-after-free bug in desktop notifications.

- .github/workflows/build-test-deploy.yaml
- android/cross-compile/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/137)
> chore: Fix android nightly/release upload.

- CMakeLists.txt
- windows/cross-compile/build.sh
Just so we can run it and observe its stdout/stderr. We do have a debug log, but if it crashes before writing that log, we can't see it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/138)
> chore: Build windows debug builds with a console.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/141)
> chore: Trigger deploy workflows on release.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/142)
> chore: Also build/test/deploy on pre-releases.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/143)
> chore: Third attempt at fixing prerelease building.

- .github/workflows/build-test-deploy.yaml
Our release process here is a bit less automated. We need to manually push a tag and then release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/144)
> chore: Undo the release deploy stuff.

- src/widget/form/tabcompleter.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/150)
> fix: Correct the tab completion regex so it works with Qt6.

- src/widget/about/aboutfriendform.cpp
- src/widget/contentdialog.cpp
- src/widget/form/chatform.cpp
- src/widget/form/conferenceform.cpp
- src/widget/form/genericchatform.cpp
- src/widget/form/genericchatform.h
- src/widget/form/setpassworddialog.cpp
- src/widget/tool/flyoutoverlaywidget.cpp
- src/widget/tool/screenshotgrabber.cpp
- src/widget/widget.cpp
The new style is compile-time checked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/151)
> cleanup: Use function pointer slots instead of old style strings.

- CMakePresets.json
- src/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/152)
> chore: Add CMake presets for IDEs (now) and CI (later).

- src/net/updatecheck.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/157)
> chore: update update url to toktok

- src/widget/form/genericchatform.cpp
Should resolve #149
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/159)
> fix: memory error on exit

- .ci-scripts/build-qtox-linux.sh
- src/net/updatecheck.cpp
- src/net/updatecheck.h
- src/widget/form/settings/aboutform.cpp
- src/widget/form/settingswidget.cpp
- src/widget/widget.cpp
Fixes #160.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/161)
> fix: Allow building qtox without update check.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/165)
> chore: Run deploy workflows on tags.

- .github/ISSUE_TEMPLATE/bug.yaml
- src/widget/form/settings/aboutform.cpp
- src/widget/form/settings/aboutform.h
- src/widget/form/settingswidget.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/181)
> chore: Make About -> File bug link use the new form-based bug report.

- translations/de.ts
- translations/nl.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/177)
> docs: Translations update from Hosted Weblate

- .github/workflows/build-test-deploy.yaml
- docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/182)
> chore: Add a debug build for Android APK.

- .weblate
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/183)
> chore: Point weblate config at the new hosted weblate project.

- src/appmanager.cpp
Right now, multi-line messages will start with a prefix but then have no prefix for the following lines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/199)
> cleanup: Prefix multi-line log messages with the same timestamp.

- .github/workflows/build-test-deploy.yaml
- CMakeLists.txt
- src/platform/posixsignalnotifier.cpp
Mainly to test that it can be done, and also to show users how to, given that openal-soft has special needs on this platform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/211)
> chore: Add arm64 macOS user build.

- audio/resources/audio_res.qrc
- res.qrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/214)
> cleanup: Sort Qt resource files by filename.

- .github/workflows/build-test-deploy.yaml
Saves time on most PR builds. Users can add the `packaging` label to force building everything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/221)
> chore: Reduce default number of PR CI builds.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/222)
> cleanup: Reduce repetition in Android build workflow.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/224)
> chore: Fix nightly apk upload.

- .github/workflows/build-test-deploy.yaml
- CMakeLists.txt
- android/6.2.4/AndroidManifest.xml
- android/6.8.1/AndroidManifest.xml
- android/cross-compile/build.sh
- docker-compose.yml
- src/appmanager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/219)
> chore: Add armeabi-v7a build.

- .github/workflows/build-test-deploy.yaml
Only flatpak doesn't yet.
Fixes #220.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/225)
> chore: Add ccache to most builds.

- src/appmanager.cpp
- src/core/core.cpp
- src/core/coreav.cpp
- src/core/corefile.cpp
- src/ipc.cpp
- src/persistence/db/rawdatabase.cpp
- src/persistence/db/upgrades/dbupgrader.cpp
- src/persistence/globalsettingsupgrader.cpp
- src/persistence/personalsettingsupgrader.cpp
- src/persistence/profile.cpp
- src/persistence/settings.cpp
- src/platform/camera/directshow.cpp
- src/video/cameradevice.cpp
- src/widget/form/settings/advancedform.cpp
- src/widget/qrwidget.cpp
- src/widget/widget.cpp
Also be a little less shouty in logs (fewer exclamation marks).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/226)
> cleanup: Avoid double spaces in logging.

- src/appmanager.cpp
Android doesn't have it. This code works everywhere (so far).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/229)
> refactor: Remove the need for `<filesystem>` in logging.

- util/include/util/interface.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/235)
> cleanup: Remove duplicate definition of DECLARE_SIGNAL.

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/242)
> docs: Add some more context to the "filing an issue" section.

- .dockerignore
- .gitignore
- CMakePresets.json
- src/model/debug/debuglogmodel.cpp
- src/model/debug/debuglogmodel.h
- src/widget/form/debug/debuglog.cpp
- src/widget/form/debug/debuglog.h
Most users won't need this widget. As a result, clicking the tab will now have a bit of a delay, but that's ok.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/238)
> perf: Delay debug log loading to show time.

- .github/workflows/build-test-deploy.yaml
See https://github.com/TokTok/qTox/actions/runs/12339539321/job/34435907081 for why.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/245)
> chore: Don't build Debug builds on release tag pushes.

- .github/release-drafter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/246)
> chore: Raise the minor version number on feature releases.

- src/model/debug/debugobjecttreemodel.cpp
- src/widget/form/chatform.cpp
- src/widget/form/chatform.h
- src/widget/form/genericchatform.h
- src/widget/form/settings/userinterfacesettings.ui
- src/widget/widget.cpp
Also some other minor cleanups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/252)
> cleanup: Remove duplication of widget IDs.

- CMakePresets.json
In accordance with the static build on CI. This makes local testing agree with CI checks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/255)
> chore: Add static cmake preset.

- smileys/EmojiOne/emoticons.xml
- smileys/Universe/emoticons.xml
This is aligned with the `;P` emoji in qTox as well as other chat apps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/264)
> cleanup: Make the tongue emoji `:P` output 😛 instead of 😋.

- .clang-format
- src/platform/camera/avfoundation.mm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/257)
> style: Format Objective C++ files with clang-format.

- src/persistence/db/rawdatabase.cpp
- src/persistence/db/rawdatabase.h
- src/persistence/profile.cpp
- src/video/cameradevice.cpp
One remains in some Windows code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/262)
> cleanup: Remove most uses of `goto`.

- .github/workflows/coverity-scan.yml
https://github.com/TokTok/qTox/actions/runs/12444818299/job/34745471594?pr=271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/271)
> chore: Add coverity scan static analysis.

- src/video/videoframe.cpp
Recursive deletion could happen if a frame is deleted in untrackFrames,
i.e. the weak_ptr is locked into a shared_ptr (2 references), then its
previous reference disappears (1 reference left), and then the
shared_ptr goes out of scope (0 references -> delete). The destructor
then locks the refsMap while inside the untrackFrames loop which has it
locked already.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/278)
> fix: Fix occasional deadlock in ending a video call.

- flatpak/io.github.qtox.qTox.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/289)
> chore: Use flatpak dependencies from releases instead of local paths.

- .github/workflows/build-test-deploy.yaml
- BUILD.bazel
- CMakeLists.txt
- flatpak/io.github.qtox.qTox.json
- flatpak/localize_flathub_descriptor.py
- flatpak/update_flathub_descriptor_dependencies.py
- src/video/videoframe.cpp
https://raw.githubusercontent.com/flathub/io.github.qtox.qTox/refs/heads/master/io.github.qtox.qTox.json
Also fixed the version updater script to use the new directory layout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/287)
> chore: Use the same flathub manifest as flathub.

- INSTALL.md
We need toxcore 0.2.20 now.
See https://github.com/TokTok/qTox/issues/277
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/279)
> docs: Update dependency documentation.

- CMakePresets.json
- src/widget/contentlayout.cpp
Fixes #304.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/305)
> fix: Don't crash on logout.

- .github/workflows/build-test-deploy.yaml
- src/widget/form/settings/avform.cpp
- util/CMakeLists.txt
- util/include/util/ranges.h
- util/src/ranges.cpp
We need to support an older C++ library that doesn't have ranges.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/309)
> cleanup: Fix compilation for Android 7.

- src/appmanager.cpp
- src/nexus.cpp
- src/nexus.h
- src/persistence/profile.cpp
- src/persistence/profile.h
Fixes #304.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/308)
> fix: Don't crash when closing the app after logout.

- .ci-scripts/build-macos-deps.sh
- .ci-scripts/build-macos-qt.sh
- .ci-scripts/macos_install_deps.sh
Slightly nicer log messages this way, showing which dep a message comes from.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/311)
> cleanup: Add dep name in the log message file path on macOS.

- macos/asan.supp
- src/widget/widget.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/315)
> cleanup: Don't connect to NULL window handle's signals.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/327)
> chore: Only run the PR validator on pull requests.

- .cirrus.yml
- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/333)
> chore: Fix appimage release build (`-` instead of `.`).

- .ci-scripts/build-macos-qt.sh
- .ci-scripts/macos_install_deps.sh
- .gitignore
- CMakePresets.json
- macos/run-debug
- src/video/camerasource.cpp
- src/video/corevideosource.cpp
- src/video/videoframe.cpp
- src/video/videoframe.h
By never having non-shared_ptr versions of it in any code other than private factories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/322)
> cleanup: Ensure VideoFrame memory is never leaked.

- src/BUILD.bazel
- test/BUILD.bazel
- test/persistence/serialize_fuzz_test.cpp
They are safe now, but still adding a fuzz test just to be sure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/336)
> test: Add a fuzz test for the remaining 2 serialize functions.

- .github/workflows/build-test-deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/342)
> chore: Allow workflow dispatch to trigger _all_ jobs.

- tools/create_release.py
- tools/lib/github.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/344)
> chore: Some more fixes to the releaser script.

- tools/translate.py
- translations/jbo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/349)
> cleanup: Fix Lojban translation a bit.

- translations/ar.ts
- translations/pl.ts
- translations/pr.ts
- translations/sr_Latn.ts
- translations/sv.ts
- translations/ta.ts
- translations/ug.ts
These are almost certainly mistakes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/351)
> cleanup: Remove any double spaces in translation files.

- cspell.config.yaml
- src/widget/form/settings/generalform.cpp
- tools/translate.py
- translations/CMakeLists.txt
- translations/en_PR.ts
- translations/fa.ts
- translations/hu.ts
- translations/ja.ts
- translations/ko.ts
- translations/li.ts
- translations/nl_LI.ts
- translations/tr.ts
- translations/translations.qrc
- translations/vi.ts
- translations/zh_TW.ts
It was heavily broken and outdated. I've saved as much of it as I could. Now it will continue to be updated by `lupdate`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/353)
> fix(Languages): Recover the long lost Pirate translation.

- cspell.config.yaml
- src/widget/form/settings/generalform.cpp
- tools/translate.py
- translations/CMakeLists.txt
- translations/fa.ts
- translations/hu.ts
- translations/ja.ts
- translations/ko.ts
- translations/li.ts
- translations/tr.ts
- translations/translations.qrc
- translations/vi.ts
- translations/zh_TW.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/352)
> feat(Languages): Add Limburgish translation.

- .ci-scripts/build-docs.sh
- .ci-scripts/create-identity.sh
- .github/workflows/build-test-deploy.yaml
- CMakeLists.txt
- appimage/build.sh
- cmake/Dependencies.cmake
- src/appmanager.cpp
- src/net/updatecheck.cpp
- src/net/updatecheck.h
- src/version.cpp.in
- src/version.h
- src/version.h.in
- src/widget/form/settings/aboutform.cpp
- test/BUILD.bazel
- windows/cross-compile/build.sh
Related: #355 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/356)
> test: Check that the version on release is considered stable.

- .ci-scripts/build-docs.sh
- .ci-scripts/create-identity.sh
- .github/workflows/build-test-deploy.yaml
- CMakeLists.txt
- appimage/build.sh
- cmake/Dependencies.cmake
- cspell.config.yaml
- src/appmanager.cpp
- src/net/updatecheck.cpp
- src/net/updatecheck.h
- src/version.cpp.in
- src/version.h
- src/version.h.in
- src/widget/form/settings/aboutform.cpp
- src/widget/form/settings/generalform.cpp
- test/BUILD.bazel
- tools/translate.py
- tools/translate_ai.py
- translations/CMakeLists.txt
- translations/ber.ts
- translations/jbo.ts
- translations/li.ts
- translations/pr.ts
- translations/translations.qrc
- windows/cross-compile/build.sh
Using AI :).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/354)
> feat(Languages): Translate all of qTox to Pirate English.

- .github/workflows/build-test-deploy.yaml
See comment for reasoning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/357)
> chore: Only run the release asset verification script once a day.

- .github/workflows/build-test-deploy.yaml
- tools/create_release.py
- tools/lib/git.py
- tools/lib/github.py
Right now the releaser check prevents anyone other than the person who built the last release to commit anything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/359)
> chore: Fixes to the releaser script.

- src/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/365)
> chore: Fix version.cpp generation in bazel build.

- .github/workflows/build-test-deploy.yaml
- src/BUILD.bazel
- tools/create_release.py
- tools/lib/github.py
- tools/validate_pr.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/362)
> chore: Hide debug info behind a --debug flag in validate_pr.

- .github/workflows/release.yml
Requires https://github.com/TokTok/ci-tools/pull/89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/358)
> chore: Post warning message when we should release soon.

- .github/workflows/build-test-deploy.yaml
- tools/create_release.py
- tools/lib/github.py
This addresses the situation where release candidates go wrong and we don't actually release them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/368)
> chore: Fix releaser to support checking the current latest release.

- .ci-scripts/version-regex.sh
- tools/lib/github.py
- tools/translate.py
- tools/translate_ai.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/369)
> cleanup: Fix mypy errors in Python code.

- .cirrus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/373)
> chore: Reinstate bazel build.

- src/appmanager.cpp
- src/persistence/settings.cpp
Probably not a lot of people use these, but it's still better to be clear. This stuff is also not localised and uses logs to print errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/376)
> cleanup: Minor clarifications on command line errors.

- .ci-scripts/build-qtox-macos.sh
- .github/workflows/build-test-deploy.yaml
- INSTALL.md
- src/core/toxid.cpp
- src/core/toxid.h
- test/core/toxid_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/392)
> cleanup: ToxId needs to be copyable for Qt to pass it through signals.

- .github/workflows/build-test-deploy.yaml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/395)
> docs: Add nightly built screenshot to readme.

- .github/workflows/build-test-deploy.yaml
I missed one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/398)
> chore: Fix macOS screenshot taking.

- .ci-scripts/build-qtox-linux.sh
Using clang-fake to produce dummy outputs, because we don't actually need the compiled output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/397)
> chore: Speed up clang-tidy by not compiling code.

- appimage/build.sh
- cmake/Dependencies.cmake
We've moved toxcore to /work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/402)
> chore: Fix AppImage build.

- src/persistence/settings.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/396)
> cleanup: Make it harder to forget to close settings groups.

- test/BUILD.bazel
- test/chatlog/qimage_fuzz_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/401)
> test: Add fuzzer for kimageformats.

- windows/cross-compile/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/405)
> cleanup: Use fewer image formats on Windows.

- CMakeLists.txt
- CMakePresets.json
- cmake/Dependencies.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/409)
> cleanup: We don't compile C sources in qTox.

- tools/translate_ai.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/380)
> cleanup: Give AI more context for translations.

- .ci-scripts/build-qtox-linux-static.sh
- .ci-scripts/build-qtox-linux.sh
- .ci-scripts/build-qtox-macos.sh
- tools/translate_ai.py
- windows/cross-compile/build.sh
So we can see if anything weird is going on with the caching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/399)
> chore: Show ccache stats after builds.

- .ci-scripts/build-qtox-linux-static.sh
- .ci-scripts/build-qtox-linux.sh
- .ci-scripts/build-qtox-macos.sh
- README.md
- tools/translate_ai.py
- windows/cross-compile/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/403)
> docs: Fix readme (remove unused links, fix typo).

- src/persistence/db/rawdatabase.h
- src/persistence/db/rawdatabaseimpl.cpp
- src/persistence/db/rawdatabaseimpl.h
- src/persistence/db/upgrades/dbto11.cpp
- src/persistence/db/upgrades/dbto11.h
- src/persistence/db/upgrades/dbupgrader.cpp
- src/persistence/db/upgrades/dbupgrader.h
- src/persistence/history.cpp
- src/persistence/history.h
- test/dbutility/include/dbutility/dbutility.h
- test/dbutility/src/dbutility.cpp
- test/persistence/dbschema_test.cpp
- test/persistence/dbupgrade/dbTo11_test.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/263)
> refactor: Make database query objects move-only.

- test/BUILD.bazel
Fails layering check otherwise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/421)
> cleanup: Add missing test deps.

- src/platform/desktop_notifications/desktopnotify.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/428)
> cleanup: Add some logging for reasons why notifications might fail.

- .ci-scripts/build-qtox-linux.sh
- CMakeLists.txt
- tools/lsp_tidy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/432)
> chore: Add opt-in REPR_RCC cmake option.

- tools/create_release.py
- tools/lib/github.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/435)
> chore: Fix releaser to properly wait for builds.

- .clang-tidy
- audio/include/audio/iaudiosink.h
- audio/include/audio/iaudiosource.h
- audio/src/backend/alsink.h
- audio/src/backend/alsource.h
- src/core/core.cpp
- src/core/toxfileprogress.h
- src/core/toxoptions.cpp
- src/core/toxoptions.h
- src/model/chatlogitem.h
- src/model/message.h
- src/model/sessionchatlog.cpp
- src/net/avatarbroadcaster.h
- src/persistence/db/rawdatabase.h
- src/persistence/db/rawdatabaseimpl.cpp
- src/persistence/history.cpp
- src/persistence/history.h
- src/persistence/paths.h
- src/persistence/settings.h
- src/persistence/settingsserializer.h
- src/video/videosurface.h
- src/widget/form/filetransferlist.h
- src/widget/imagepreviewwidget.h
- src/widget/searchform.h
- src/widget/tool/activatedialog.h
- src/widget/tool/identicon.h
- test/model/friendlistmanager_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/439)
> cleanup: Use explicit constructors where possible.

- .github/workflows/build-test-deploy.yaml
- CMakeLists.txt
- cmake/Dependencies.cmake
- cmake/Testing.cmake
- src/BUILD.bazel
- src/platform/posixsignalnotifier.cpp
- src/platform/stacktrace.cpp
- src/platform/stacktrace.h
- test/BUILD.bazel
- test/platform/stacktrace_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/442)
> feat(Debug): Add stack trace logging on crash.

- test/model/notificationgenerator_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/446)
> test: Get better error messages in notification test.

- src/platform/capslock_osx.cpp
- src/platform/timer_osx.cpp
- src/widget/translator.cpp
- src/widget/translator.h
They renamed master to main, because everybody is doing that these days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/448)
> cleanup: Add support for macOS before 12.0.

- src/platform/capslock_osx.cpp
- src/platform/timer_osx.cpp
For Bot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/450)
> cleanup: Use braces initialiser for io_service_t.

- .ci-scripts/build-qtox-macos.sh
- .ci-scripts/local_install_deps.sh
- .github/workflows/build-test-deploy.yaml
- src/platform/capslock_osx.cpp
- src/platform/timer_osx.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/451)
> chore: Add a macos-10.15 build.

- .circleci/bazel-test
- .circleci/config.yml
- .cirrus.yml
- cmake/Dependencies.cmake
On cirrus, we now build on their local image with their local cache. Let's see if that's any better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/456)
> chore: Move toktok-stack test to circleci.

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/465)
> chore: Add issue type to the issue templates.

- .ci-scripts/build-qtox-linux.sh
- .cirrus.yml
- src/persistence/profile.cpp
- src/widget/widget.cpp
- test/dbutility/src/dbutility.cpp
Clang-tidy failed to fix these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/466)
> cleanup: Mark some more variables as `const`.

- src/chatlog/content/text.cpp
- src/core/core.cpp
- src/core/coreav.cpp
- src/model/friendlist/friendlistmanager.cpp
- src/persistence/paths.cpp
```sh
run-clang-tidy -p _build -fix $(find . -name "*.h" -or -name "*.cpp" \
-or -name "*.c" | grep -v "/_build/") \
-checks="-*,readability-simplify-boolean-expr"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/84)
> cleanup: Simplify boolean returns.

- .github/workflows/build-test-deploy.yaml
- CMakeLists.txt
- audio/src/backend/openal.cpp
- cmake/Dependencies.cmake
- docker-compose.yml
- platform/wasm/build.sh
- src/appmanager.cpp
- src/core/toxlogger.cpp
- src/ipc.cpp
- src/ipc.h
- src/main.cpp
- src/persistence/profilelocker.cpp
- src/platform/posixsignalnotifier.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/480)
> feat(Web): Preliminary support for running qTox in the browser.

- .github/workflows/build-test-deploy.yaml
- netlify.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/481)
> chore: Deploy webqtox to Netlify.

- .github/workflows/build-test-deploy.yaml
We're doing it manually now with the netlify CLI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/483)
> chore: Fix netlify deploy.

- .github/workflows/build-test-deploy.yaml
- netlify.toml
- platform/wasm/_headers
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/485)
> chore: Fix netlify headers so webqtox can work.

- .dockerignore
- .github/workflows/build-test-deploy.yaml
- platform/wasm/Dockerfile
- platform/wasm/run.sh
This can be used for local testing and development as well as render.com deployment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/484)
> chore: Add a wasm run dockerfile.

- .dockerignore
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/492)
> docs: Update README to have the correct nightly macOS links.

- src/appmanager.cpp
- src/core/core.cpp
- src/core/core.h
- src/nexus.cpp
- src/nexus.h
- src/persistence/profile.cpp
- src/persistence/profile.h
- src/persistence/settings.cpp
- src/persistence/settings.h
- src/widget/form/settings/advancedform.cpp
- src/widget/widget.cpp
- test/core/core_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/496)
> refactor: A bit of cleanup in tox/profile creation/loading.

- .ci-scripts/package-qtox-linux.sh
- .github/workflows/build-package.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/509)
> chore: Use ninja build in rpm package job.

- .dockerignore
- platform/wasm/build.sh
It silently failed to add the _headers file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/511)
> chore: Fix deploy preview.

- src/widget/form/settings/advancedform.cpp
- src/widget/form/settings/advancedform.h
Fixes https://github.com/TokTok/qTox/issues/523
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/527)
> fix(About): Retranslate the important message when changing language.

- res/nodes.json
One IP changed, some bootstrap node versions changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/532)
> chore: Update nodes.json.

- CHANGELOG.md
We must have an h3 to lead into the release notes/changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/541)
> docs: Update changelog to new format requirements.

- README.md
Maybe some people will come chat with us :).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/535)
> docs: Add groupbot and NGC chat to the readme.

- tools/update-versions.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/539)
> chore: Add CMakeLists.txt version updater.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/540)
> docs: Update readme to no longer say we're unofficial.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/554)
> docs: Fix macOS screenshot in readme.

- src/widget/form/settings/aboutform.cpp
Fixes #555.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/556)
> fix: Use correct bug template in report bug button.

- src/persistence/settings.cpp
- src/persistence/settings.h
Reduces duplication and makes things a bit more standard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/568)
> cleanup: Push more code into generic settings functions.

- .gitignore
- cmake/Testing.cmake
- src/widget/tool/identicon.cpp
- src/widget/tool/identicon.h
- test/widget/tool/identicon_test.cpp
- tools/lsp_tidy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/521)
> test: Add a test for the identicon calculation.

- translations/ar.ts
- translations/ber.ts
- translations/bn.ts
- translations/da.ts
- translations/el.ts
- translations/eo.ts
- translations/he.ts
- translations/is.ts
- translations/ja.ts
- translations/jbo.ts
- translations/kn.ts
- translations/ko.ts
- translations/li.ts
- translations/lv.ts
- translations/mk.ts
- translations/si.ts
- translations/sl.ts
- translations/sq.ts
- translations/sw.ts
- translations/ug.ts
- translations/ur.ts
- translations/zh_CN.ts
- translations/zh_TW.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/574)
> cleanup: Add spaces to generated translations of MB/px.
