TokTok/qTox

BUILD.bazel
src/core/core.cpp
src/widget/widget.cpp
test/BUILD.bazel

See https://github.com/TokTok/c-toxcore/pull/295.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/qtox/7)

Adapt qtox to new conferences state change callback.

---

BUILD.bazel
audio/BUILD.bazel
src/BUILD.bazel
test/BUILD.bazel
util/BUILD.bazel

This way we can do bazel build //... when cross-compiling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/35)

chore: Disable targets for cross-compilation.

---

BUILD.bazel

Needed for remote-exec, because it doesn't support Qt, yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/36)

chore: Add some more things to no-cross.

---

.github/workflows/release.yml

Requires https://github.com/TokTok/toktok-stack/pull/865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/47)

chore: Cancel old release-check runs when pushing new commits.

---

.cirrus.yml

We have 16 in total (8 can be used at the same time). This means that now we can only build 2 qtox PRs at the same time, but hopefully they will finish faster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/100)

chore: Give Cirrus more CPUs to build qtox.

---

src/widget/form/settings/userinterfaceform.cpp
src/widget/form/settings/userinterfaceform.h
src/widget/form/settings/userinterfacesettings.ui

Found this typo while changing "group" to "conference" in #92.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/93)

cleanup: Fix typo "groupOnlyNotfiyWhenMentioned"

---

src/widget/form/settings/userinterfaceform.cpp
src/widget/form/settings/userinterfaceform.h

It didn't do anything. Now it can correctly select different styles again (Windows and Fusion).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/96)

fix: Fixed the style selector in UI settings.

---

.github/workflows/build-test-deploy.yaml

They overwrite each other without this, causing one job to never have a cache and always missing every cache lookup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/107)

chore: Use separate cache keys for the jobs using ccache.

---

src/widget/style.cpp

This multiplication used to be necessary, but isn't anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/95)

fix: Don't create huge font weights in themes.

---

themes/default/window/general.css

Before: 
After: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/105)

fix: Make checkboxes more visible on wayland.

---

CMakeLists.txt
src/BUILD.bazel
src/net/toxuri.cpp
src/widget/form/filesform.cpp
src/widget/form/filesform.h
src/widget/form/filetransferlist.h

This fixes some warnings we get from the translation string updater.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/111)

cleanup: Make filesform.h and toxuri.cpp parseable by Linguist.

---

util/include/util/toxcoreerrorparser.h
util/src/toxcoreerrorparser.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/117)

cleanup: Make tox error code logging originate from calling code.

---

src/platform/camera/avfoundation.mm

I missed this one when changing C++ files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/124)

cleanup: Add spdx license header to our only ObjC++ file.

---

.ci-scripts/build-osx-deps.sh
.ci-scripts/build-qtox-macos.sh
.github/workflows/build-test-deploy.yaml
osx/Brewfile-DepBuildDeps

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/139)

chore: Add macos-14 build for Apple Silicon.

---

CMakeLists.txt

A little bit of irony there in this one.  :]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/146)

cleanup: Fix typo in spellcheck CMake option.

---

cmake/Dependencies.cmake

Not sure if something like this will be wanted, and not sure if it catches all the platforms and such (also the formatting gets a bit wide-like), but at this time, the build fails as follows with toxcore version less than 0.2.20:
```
FAILED: util/CMakeFiles/util_library.dir/src/toxcoreerrorparser.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DCMAKE_BUILD -DDESKTOP_NOTIFICATIONS=0 -DGIT_DESCRIBE=\"nightly\" -DGIT_DESCRIBE_EXACT=\"nightly\" -DGIT_VERSION=\"9270753a8686706a33adeecea90eb138d789f466\" -DLOG_TO_FILE=1 -DQTOX_PLATFORM_EXT -DQT_CORE_LIB -DQT_MESSAGELOGCONTEXT=1 -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_RESTRICTED_CAST_FROM_ASCII -DSPELL_CHECKING -I/mnt/lprup/portage-build/portage/net-im/qtox-9999/work/qtox-9999_build/util/util_library_autogen/include …
```

chore: Add version check for toxcore.

---

src/core/toxstring.cpp
src/core/toxstring.h
test/core/toxstring_test.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/148)

fix(security): Only allow printable characters in incoming messages.

---

CMakeLists.txt

See https://github.com/TokTok/qTox/issues/172 by @ljgdasfhk.
This should make the APK work on older Android versions. In the android builder image, we [already select API 23](https://github.com/TokTok/dockerfiles/blob/15f3ca2ebb2715ff09ffb97569c3299836d2f22a/qtox/docker/Dockerfile.android-builder#L41), so this should work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/173)

chore: Set min sdk version to 24 (Android 7).

---

test/BUILD.bazel

We're not ready for ARM builds of ffmpeg.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/184)

chore: Don't build Qt stuff in bazel cross-compile builds.

---

src/core/core.cpp
src/core/core.h
src/persistence/db/upgrades/dbto11.cpp
src/video/cameradevice.cpp
src/widget/categorywidget.cpp
src/widget/chatformheader.cpp
src/widget/chatformheader.h
src/widget/form/chatform.cpp
src/widget/widget.cpp

Also recieve -> receive.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/178)

cleanup: Another typo fix, avaliable -> available.

---

src/core/core.cpp
src/core/corefile.cpp
src/persistence/profile.cpp

These constants can change from version to version, so we should use a runtime version of them rather than encoding the number into our binary at compile time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/174)

cleanup: Use tox core "length" functions instead of constants.

---

CMakePresets.json

There's no way to build without desktop notifications now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/189)

cleanup: Remove now unused DESKTOP_NOTIFICATIONS from cmake preset.

---

src/core/coreav.cpp
util/CMakeLists.txt
util/include/util/algorithm.h
util/src/algorithm.cpp

You shouldn't iterate over a container and modify it at the same time (unless you do `it = c.erase(...)` which this code can't do, and you can't do in range-for anyway.
Fixes #180.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/192)

fix: Fix use-after-free when closing qTox during a call.

---

src/core/core.cpp
src/core/coreav.cpp
src/core/corefile.cpp
src/persistence/settings.cpp

QStrings are quoted by default, making log messages a bit weird.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/122)

cleanup: Avoid logging QString as format.

---

BUILD.bazel
audio/BUILD.bazel
src/BUILD.bazel
src/chatlog/chatlinecontentproxy.cpp
src/chatlog/chatlinecontentproxy.h
src/chatlog/chatwidget.cpp
src/core/core.cpp
src/persistence/settings.cpp
src/widget/categorywidget.cpp
src/widget/contentdialog.cpp
src/widget/contentdialogmanager.h
test/BUILD.bazel
test/core/fileprogress_test.cpp
test/model/sessionchatlog_test.cpp
util/BUILD.bazel

Also tag targets as `qt` instead of `no-cross` to have more precision in selecting targets in various bazel builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/198)

cleanup: Some random warning cleanups and some typo fixes.

---

test/core/core_test.cpp

In some cases and on some systems, "Test" is a valid proxy address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/197)

test: Make the invalid proxy test less flaky.

---

src/BUILD.bazel

Requires https://github.com/TokTok/toktok-stack/pull/906.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/202)

chore: Use `mkstamp` macro to get git version from bazel build.

---

CMakeLists.txt

Qt occasionally does `dynamic_cast` and there's no (good) way of disabling RTTI in Qt builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/204)

chore: Enable rtti in all builds.

---

src/widget/contentlayout.cpp
src/widget/form/debugwidget.cpp

The debug widget one is a one-off, but the content layout accumulates over time and gets worse, as it's created multiple times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/205)

fix: Fix two memory leaks.

---

cmake/Dependencies.cmake

I couldn't build the project without a couple of edits to the cmake file, everything was working before.
- `${TOXCORE_VERSION}` is only available if pkg_check_modules was successful.
- The project should be also linked against `toxav` and `toxencryptsave` which are installed by toxcore's cmake file.
Signed-off-by: Nikolay Borodin <monsterovich@gmail.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/206)

fix: cmake file dependencies

---

src/persistence/smileypack.cpp
src/persistence/smileypack.h

It takes 10ms to load the file. There's no need to do this in a separate thread anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/215)

cleanup: Stop loading smileypack in a separate thread.

---

.github/workflows/build-test-deploy.yaml

PR builds are equivalent for these jobs, as they don't output any artifacts. There's no need to run them twice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/223)

chore: Don't run non-deploy jobs on push (only PR).

---

BUILD.bazel

The macro sets up the right environment for `bazel run :qtox` to find the platform, network, and image format plugins.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/201)

chore: Use qt_binary instead of cc_binary for qtox.

---

windows/cross-compile/build.sh

Some of these aren't working still.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/154)

test: Re-enable tests on windows.

---

.ci-scripts/build-qtox-linux-static.sh
.github/workflows/build-test-deploy.yaml
CMakeLists.txt
cmake/Dependencies.cmake
docker-compose.yml
src/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/227)

chore: Add fully static qtox build.

---

windows/cross-compile/build.sh
windows/cross-compile/check-dlls

This is just for local compilation so we don't need to keep deleting `_build` and can instead build both in the same source directory.
Also removed some unused code for wine dll prefixes.
Needs https://github.com/TokTok/dockerfiles/pull/184
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/228)

chore: Build windows outputs into arch-specific build dirs.

---

src/widget/form/settings/userinterfaceform.cpp

Right now it's showing the last few elements of the smiley list, which is some countries flags. We should show the first ones, which is faces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/231)

fix: Show actual smileys in the smileypack selector.

---

src/appmanager.cpp

In case someone has `/src/` in the path leading up to qtox source root.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/237)

fix: Use the *last* `/src/` to find the source root.

---

.imgbotconfig

We like them readable. Actual resource compression is much more effective for saving space in binaries than the 7% savings by removing spaces and making them unreadable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/241)

chore: Don't imgbot-optimise SVGs.

---

.github/workflows/build-test-deploy.yaml

The action we were using was doing something wrong and couldn't reuse caches from master builds, making each first PR build really slow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/243)

chore: Fix ccache cache sharing.

---

CMakeLists.txt
audio/src/backend/openal.cpp
src/chatlog/content/text.cpp
src/core/core.cpp
src/core/core.h
src/net/updatecheck.cpp
src/widget/widget.cpp
src/widget/widget.h

Also don't implicit-cast string to `QUrl`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/249)

cleanup: Reduce amount of implicit casting in signals/slots.

---

CMakeLists.txt
src/core/toxcall.cpp
src/net/avatarbroadcaster.cpp
src/nexus.cpp
src/video/netcamview.cpp
src/widget/circlewidget.cpp
src/widget/form/conferenceform.cpp
src/widget/form/conferenceinviteform.cpp
src/widget/form/conferenceinvitewidget.cpp
src/widget/form/debug/debuglog.cpp
src/widget/form/filesform.cpp
src/widget/form/settings/aboutform.cpp
src/widget/friendlistwidget.cpp
src/widget/friendwidget.cpp
src/widget/widget.cpp
test/widget/filesform_test.cpp

To ensure signals are disconnected when target objects go out of scope.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/248)

cleanup: Avoid contextless `connect`.

---

.ci-scripts/.gitignore
.ci-scripts/build-macos-qt.sh
.ci-scripts/build-macos-qtdeps.sh
.ci-scripts/build-qtox-macos.sh
.ci-scripts/macos_install_deps.sh
.github/workflows/build-test-deploy.yaml
CMakeLists.txt
CMakePresets.json
cmake/Dependencies.cmake
cmake/Testing.cmake
macos/Brewfile-DepBuildDeps
src/main.cpp
test/persistence/smileypack_test.cpp

This way we can avoid the buggy macdeployqt entirely. Unfortunately, CrowdStrike doesn't like the modified binaries it produces and kills qTox on startup (unless running in `lldb`).
Related: https://github.com/Mozilla-Ocho/llamafile/issues/14
Requires:
- https://github.com/TokTok/dockerfiles/pull/185
- https://github.com/TokTok/dockerfiles/pull/187
- https://github.com/TokTok/dockerfiles/pull/190
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/254)

chore: Build all deps including Qt statically on macOS.

---

src/core/core.cpp
src/persistence/settings.cpp

This causes the log output to put quotes around the message. E.g.
```
[16:06:12.863 UTC] src/persistence/settings.cpp:95 : Debug: "Loading settings from :/conf/qtox.ini"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/258)

cleanup: Avoid string concatenation in log output.

---

src/appmanager.cpp
src/model/debug/debuglogmodel.cpp
src/model/debug/debuglogmodel.h

This is useful to distinguish log sources. In the future, we can use this to e.g. make more verbose logging optional or allow category-filtering in the debug log view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/256)

refactor: Add logging category to debug log.

---

src/core/toxlogger.cpp

Toxcore already cleans this path and only passes the filename. This path cleaner wasn't great to begin with (requiring the source directory name to be c-toxcore).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/266)

cleanup: Remove unnecessary path cleaner in tox logger.

---

.github/workflows/build-test-deploy.yaml

It seems to frequently fail to unmount because the device is busy. This PR hopes that trying more will eventually succeed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/269)

chore: Reduce flakiness of macOS builds.

---

util/src/toxcoreerrorparser.cpp

We still recommend using newer toxcore, but this at least makes it compile.
Fixes https://github.com/TokTok/qTox/issues/277
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/280)

chore: Support toxcore 0.2.19 and below.

---

src/video/videoframe.cpp
src/video/videoframe.h

There's a deadlock somewhere in here. I'm not sure how it happens, yet, but this will at least mostly eliminate the possibility of forgotten unlocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/275)

cleanup: Use mutex lockers where possible in video frame handling.

---

src/core/toxcall.cpp
src/core/toxcall.h

The problem here was that during the destruction of ToxFriendCall's, audio frames can still be sending. The fix here is very ugly: instead of connecting the audioSource to the call, we directly connect it to CoreAV. This is the same as we currently do for video source -> CoreAV. It's unclear to me whether this is at all safe to do, so maybe some weirdness happens to calls during shutdown, but at least no undefined behaviour should happen during ToxFriendCall destruction now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/274)

fix: Don't crash on quit during AV call.

---

audio/src/backend/openal.cpp
audio/src/backend/openal.h
macos/info.plist
src/core/toxcall.cpp
src/platform/camera/avfoundation.h
src/platform/camera/avfoundation.mm
src/video/cameradevice.cpp
src/video/videomode.cpp
src/video/videomode.h
src/widget/form/settings/avform.cpp

It was broken with newer ffmpeg versions. This change aligns the device input names with the expectation of newer ffmpeg. Tested against 7.1, but it's the same on 6.x and maybe some versions before as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/267)

fix: Make camera input work again on macOS.

---

src/platform/camera/avfoundation.mm

This blocks the main thread and is not ideal, but it's better than the undefined behaviour it has at the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/283)

fix: Make sure camera access is gained on macOS before calling.

---

src/model/ichatlog.h
src/model/message.h
util/include/util/strongtype.h

Coverity tripped over this. In reality this is probably fine, but the cost of this extra initialisation is negligible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/272)

cleanup: Ensure message structs don't have uninitialised members.

---

src/core/coreav.cpp
src/core/coreav.h
src/widget/form/settings/avform.cpp

There's a crashing bug in the AV code caused by changing the video device during a call. The fix for that is non-trivial. In the meantime, we disallow such changes to make sure users don't crash themselves.
See https://github.com/TokTok/qTox/issues/281
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/284)

fix: Disable video device selection box during call.

---

src/appmanager.cpp

Some of these are extremely noisy. Probably we should distinguish toxcore and toxav categories into tox.core and tox.av, but right now that's not doable without hard-coding all the toxav filenames.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/273)

perf: Don't log verbose toxav messages.

---

.github/workflows/build-test-deploy.yaml

Also cleaned up the `get_version` step. It now does the same as the apk equivalent and no longer uses a deprecated way of producing step-outputs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/290)

chore: Use ccache in flatpak build.

---

src/video/videoframe.h

This hashtable used std::function dispatch to a function pointer for no good reason. It could have just used the function pointer instead. Now we use neither and statically bind the hash function to the hash map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/276)

perf: Improve performance of video frame buffering.

---

CMakeLists.txt
src/core/core.cpp
src/platform/camera/avfoundation.h
src/platform/camera/avfoundation.mm
src/platform/camera/directshow.cpp
src/platform/camera/v4l2.cpp
src/platform/camera/v4l2.h
src/video/cameradevice.cpp
src/video/camerasource.cpp
src/video/scopedavdictionary.cpp
src/video/scopedavdictionary.h
src/video/videomode.cpp
src/video/videomode.h
src/widget/form/settings/avform.cpp
test/core/core_test.cpp

This would happen e.g. on activating screen capture, but then denying permissions for it in the popup dialog. This doesn't exactly hang the program, but prevents any further changes to the capture device setting, and will hang the program on shutdown (in the destructor of the camera device).
The drive-by cleanups seem to have fixed the crash when changing video devices as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/300)

fix: Avoid hanging when capture device permissions denied on macOS.

---

src/widget/circlewidget.cpp

`isCompact` reads from `this->compact`, which isn't ready yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/314)

fix: Fix uninitialised read in contact circle widget.

---

macos/Brewfile
macos/Brewfile-DepBuildDeps
macos/createdmg
macos/update-plist-version.sh

macOS comes with bash v3, which doesn't do arrays. We can't comply with restyled/codacy requirements without arrays.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/321)

chore: Install homebrew bash v5.

---

.ci-scripts/build-qtox-macos.sh
src/widget/form/filesform.cpp

Needs https://github.com/TokTok/dockerfiles/pull/221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/323)

cleanup: Don't use deprecated spelling of tox enums.

---

.ci-scripts/create-identity.sh
.ci-scripts/validate-pr.py
.clog.toml
.github/workflows/build-test-deploy.yaml
CHANGELOG.md
MAINTAINING.md
tools/sync-changelog-tags.py
tools/update-changelog.py

The rust clog doesn't work, so I rewrote it. This one also supports forks so doesn't depend on a single URL always working, and always fully regenerates the entire log. This found a few broken entries from the old changelog that will now be corrected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/328)

chore: Rewrite clog (more correctly) in Python.

---

tools/sync-changelog-tags.py

Example output:
```
--------------------
Updating tag message for v1.4.0
>>>>>>>>
qTox 1.4.0 release
More information in CHANGELOG.md
========
Time flows, and with the flow come new features, new bugfixes, and hopefully no
new bugs.
With this release, a partial changelog of changes since 1.3.0 is added.
Next release will contain a changelog with all changes.
We are hoping that you'll enjoy the new stuff.
Cheers. :)
_PS._ If it's not clear from the changelog below, audio groupchats have been
~fixed.
Original tagger: sudden6 <sudden6@gmx.at> 1461505061 +0200
<<<<<<<<
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/325)

chore: Add script for syncing CHANGELOG.md to git tags.

---

.github/workflows/build-test-deploy.yaml
appimage/build.sh
docker-compose.yml
src/widget/form/genericchatform.cpp

things still to do:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/306)

feat: add appimage back to ci

---

src/persistence/serialize.cpp
src/persistence/serialize.h

These ought to be used with safe data, but who knows whether they actually are. Now, these functions will never fatally misbehave.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/335)

fix(Security): Harden the persistence/serialization functions.

---

.ci-scripts/macos_install_deps.sh
.github/workflows/build-test-deploy.yaml
src/core/coreav.cpp
src/platform/camera/avfoundation.mm
src/video/videoframe.cpp
src/video/videoframe.h

There was an AV race condition caused by clearing the frame buffer while the VideoFrame is in flight towards toxav. The fix is heavy-handed in that we're now just copying the frame every time, even though we almost never have this problem (only when changing devices). So we pay the cost all the time even though it's rarely needed. However, this is a serious crashing bug (heap-use-after-free), so I'd rather have it fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/312)

fix: Avoid occasional crash when changing video devices or closing qTox.

---

.cirrus.yml
.github/workflows/build-test-deploy.yaml

Running them outside the builder images to make sure they are somewhat portable and work on ubuntu-22.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/340)

chore: Add test workflows for appimage/flatpak binaries.

---

cmake/Dependencies.cmake
src/appmanager.cpp
src/net/updatecheck.cpp
src/version.h.in
src/widget/form/settings/aboutform.cpp

This avoids having to do a full rebuild when any of the git describe stuff changes (which is all the time). This greatly speeds up ccache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/339)

cleanup: Use version.h in cmake build as well.

---

src/core/coreav.cpp
src/video/videoframe.cpp
src/video/videoframe.h

We need to extend the frame buffer lock a little more by returning it to the caller, but this way we can avoid copying frames (which can be quite large here).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/337)

perf(Video): Avoid copying frame buffers unnecessarily.

---

src/chatlog/chatwidget.cpp
src/persistence/db/upgrades/dbto11.cpp
src/persistence/db/upgrades/dbupgrader.cpp

clang-tidy: modernize-use-emplace
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/90)

cleanup: Use emplace_back instead of push_back.

---

.clang-tidy
src/persistence/settings.cpp
src/widget/style.cpp
src/widget/style.h

If the OS/desktop environment have dark mode set, then qTox will select the default dark color scheme as well.
Also, if the user sets light mode, this sets Qt to light mode as well. This avoids conflicting style hints resulting in invisible text (dark grey on black).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/261)

feat(UI): Better integration with system dark modes.

---

.clang-tidy
src/core/toxfile.h
src/model/conference.cpp
src/model/exiftransform.cpp

clang-tidy: modernize-use-bool-literals
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/91)

cleanup: Use `true`/`false` instead of `0`/`1` for boolean literals.

---

.github/workflows/build-test-deploy.yaml
flatpak/io.github.qtox.qTox.json

ccache changes much more often than the rest of the cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/360)

chore: Cache flatpak's ccache separately (and upgrade to KDE 6.8).

---

.ci-scripts/smoke-test.sh
.github/workflows/build-test-deploy.yaml

We run this for all our release binaries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/377)

chore: Add update-check to the CI smoke test.

---

.ci-scripts/smoke-test.sh
tools/create_release.py

Even if the current master *will* become a release build, the nightly that comes out of it should be considered an unstable non-release build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/384)

chore: Don't consider an untagged build to be stable.

---

src/core/toxstring.cpp
test/core/toxstring_test.cpp

Fixes #386.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/390)

fix(Chat): Correctly display newlines in incoming chat messages.

---

res.qrc
src/widget/form/genericchatform.cpp
themes/dark/genericChatForm/genericChatForm.qss
themes/default/genericChatForm/genericChatForm.qss

We don't need the background stylesheet anymore, because we use Qt style hints. Also, testing without those style hints it still works fine, so there seems to be some redundancy in setting backgrounds for widgets.
Fixes #387.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/388)

fix(UI): Message edit context menu now changes colour to hover/selection

---

src/core/toxid.cpp
src/core/toxid.h
src/widget/form/addfriendform.cpp
test/core/toxid_test.cpp

We never copy it except in one place where it's a mistake.
Also removed an unimplemented member function declaration from ToxId.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/175)

cleanup: Make ToxId move-only.

---

.ci-scripts/build-local-deps.sh
CMakeLists.txt
cmake/Dependencies.cmake
src/main.cpp
src/widget/imagepreviewwidget.cpp

This needs kimageformats, which we'll be adding to the CI build over the next 1-2 PRs. For now, it'll work on macOS (once we rebuild the deps). Also for now it'll only work on our static builds. We can look into discovering the kimg dependencies in the system later on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/393)

feat(Pictures): Add QOI image format support.

---

.clang-tidy
audio/src/backend/openal.cpp
src/chatlog/chatline.cpp
src/chatlog/chatwidget.cpp
src/core/toxfileprogress.cpp
src/model/notificationgenerator.cpp
src/video/videoframe.cpp
test/model/friendmessagedispatcher_test.cpp
test/net/bsu_test.cpp

```sh
run-clang-tidy -p _build -fix \
$(find . -name "*.h" -or -name "*.cpp" -or -name "*.c" | grep -v "/_build/") \
-checks="-*,readability-container-*"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/78)

cleanup: Use `.empty()` instead of `.size() == 0`.

---

.clang-tidy
src/chatlog/chatline.cpp
src/ipc.cpp
src/model/friendlist/friendlistmanager.cpp
src/net/bootstrapnodeupdater.cpp
src/widget/form/settings/avform.cpp
src/widget/friendlistwidget.cpp
test/model/friendlistmanager_test.cpp

clang-tidy: modernize-loop-convert
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/89)

cleanup: Use range-for in more places.

---

.clang-tidy
src/chatlog/chatlinecontent.cpp
src/chatlog/chatmessage.cpp
src/chatlog/chatwidget.cpp
src/chatlog/content/broken.cpp
src/chatlog/content/image.cpp
src/chatlog/content/notificationicon.cpp
src/chatlog/content/spinner.cpp
src/chatlog/content/text.cpp
src/chatlog/content/timestamp.cpp
src/core/chatid.cpp
src/core/core.cpp
src/model/chatlogitem.cpp
src/model/conference.cpp
src/model/debug/debuglogmodel.cpp
src/model/debug/debugobjecttreemodel.cpp
src/persistence/history.cpp
src/persistence/profilelocker.cpp
src/persistence/settings.cpp
src/platform/camera/v4l2.cpp
src/video/videomode.cpp
src/widget/form/filesform.cpp
src/widget/form/genericchatform.cpp
src/widget/imagepreviewwidget.cpp
src/widget/searchform.cpp
src/widget/tool/croppinglabel.cpp
src/widget/tool/screengrabberchooserrectitem.cpp
src/widget/widget.cpp
test/mock/include/mock/mockcoreidhandler.h
test/mock/include/mock/mockcoresettings.h

```
run-clang-tidy -p _build -fix $(find . -name "*.h" -or -name "*.cpp" \
-or -name "*.c" | grep -v "/_build/") \
-checks="-*,modernize-return-braced-init-list"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/82)

cleanup: Return braced initialiser list where possible.

---

src/BUILD.bazel
src/model/exiftransform.cpp
test/BUILD.bazel
test/model/exiftransform_fuzz_test.cpp
test/model/exiftransform_test.cpp

Exif data handling had a heap buffer overflow. Not likely possible to abuse, but still not good.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/415)

fix(Security): Fix heap buffer overflow in receiving pictures.

---

tools/create_tarballs.py

This fixes the root directory name in the release tarballs, which would have a literal '{tag}' instead of the actual tag string.
Closes: https://github.com/TokTok/qTox/issues/412
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/417)

fix(tools): Use tag strings in release tarballs.

---

.clang-tidy
src/appmanager.cpp
src/chatlog/chatmessage.cpp
src/chatlog/content/filetransferwidget.cpp
src/chatlog/content/spinner.cpp
src/core/coreav.cpp
src/ipc.cpp
src/persistence/profile.cpp
src/platform/camera/v4l2.cpp
src/platform/posixsignalnotifier.cpp
src/widget/chatformheader.cpp
src/widget/emoticonswidget.cpp
src/widget/form/chatform.cpp
src/widget/form/settingswidget.cpp
src/widget/qrwidget.cpp
src/widget/tool/callconfirmwidget.cpp
src/widget/widget.cpp
test/model/friendlistmanager_test.cpp
test/persistence/dbschema_test.cpp
test/persistence/dbupgrade/dbTo11_test.cpp
test/platform/posixsignalnotifier_test.cpp
test/widget/filesform_test.cpp

Also replace deprecated C header includes with their C++ versions.
To reproduce:
```sh
run-clang-tidy -p _build -fix \
$(find . -name "*.h" -or -name "*.cpp" | grep -v "/_build/") \
-checks="-*,modernize-deprecated-headers,modernize-make-shared,modernize-make-unique"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/76)

cleanup: Use `make_unique` and `make_shared` instead of `new`.

---

src/model/notificationgenerator.cpp
src/nexus.cpp
src/platform/camera/avfoundation.mm
src/platform/desktop_notifications/desktopnotifybackend_dbus.cpp
test/model/conferencemessagedispatcher_test.cpp
test/model/friendmessagedispatcher_test.cpp
test/model/notificationgenerator_test.cpp
test/model/sessionchatlog_test.cpp
test/persistence/dbupgrade/dbTo11_test.cpp

Our clang-tidy run doesn't catch these, but clangd does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/425)

cleanup: Fix some more clang-tidy warnings.

---

CMakeLists.txt

`set(POSITION_INDEPENDENT_CODE True)` statement won't have any affect because CMake won't interpret it as a valid variable or property that controls PIC.
If we want to apply `-fPIC` flag to all targets we must use `CMAKE_POSITION_INDEPENDENT_CODE` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/423)

fix: cmake POSITION_INDEPENDENT_CODE global setting

---

.clang-tidy
src/model/debug/debugobjecttreemodel.cpp
src/model/friendlist/friendlistmanager.cpp
src/model/friendlist/friendlistmanager.h
src/video/scopedavdictionary.cpp
src/video/scopedavdictionary.h
src/widget/contentlayout.cpp
src/widget/contentlayout.h
src/widget/form/chatform.cpp
src/widget/form/chatform.h
src/widget/form/settings/avform.cpp
src/widget/form/settings/avform.h
src/widget/genericchatroomwidget.cpp
src/widget/genericchatroomwidget.h
src/widget/searchtypes.h
src/widget/tool/removechatdialog.h
src/widget/tool/screenshotgrabber.cpp
src/widget/tool/screenshotgrabber.h
src/widget/widget.cpp
src/widget/widget.h
test/model/friendlistmanager_test.cpp
test/persistence/dbschema_test.cpp

```sh
run-clang-tidy -p _build -fix \
$(find . -name "*.h" -or -name "*.cpp" -or -name "*.c" | grep -v "/_build/") \
-checks="-*,readability-make-member-function-const"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/83)

cleanup: Make member functions `const` where possible.

---

src/widget/form/genericchatform.cpp

We now also put the link into the selection clipboard in addition to the `ctrl+v` clipboard. This is the middle-click-to-paste clipboard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/440)

fix(Clipboard): Improve "copy link to clipboard" on Linux.

---

.clang-tidy
audio/src/backend/openal.cpp
src/appmanager.cpp
src/core/corefile.cpp
src/persistence/profile.cpp
src/platform/timer_x11.cpp
src/widget/flowlayout.cpp
src/widget/genericchatitemlayout.cpp
src/widget/qrwidget.cpp
src/widget/tool/callconfirmwidget.cpp
src/widget/tool/movablewidget.cpp
test/model/exiftransform_test.cpp

```sh
run-clang-tidy -p _build -fix $(find . -name "*.h" -or -name "*.cpp" \
-or -name "*.c" | grep -v "/_build/") \
-checks="-*,readability-isolate-declaration"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/85)

cleanup: Avoid multiple declarations per statement.

---

src/net/updatecheck.cpp
src/widget/form/settings/aboutform.cpp

When users run nightly builds, we still want to tell them when their nightly build has become older than the newest production release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/452)

feat(About): Show update available in nightly builds.

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature.yaml

GitHub UI says you can add issue types. "type:" doesn't work. I don't know how to do it then.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/464)

chore: Add emojis to the issue templates.

---

.clang-tidy
src/model/message.cpp
src/widget/form/tabcompleter.cpp
src/widget/tool/croppinglabel.cpp

clang-tidy: modernize-raw-string-literal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/88)

cleanup: Use raw strings to simplify regexes.

---

src/persistence/history.cpp

In this PR we are removing the assertion that the logging is on, when user tries to get the friend information. This assertion causes qTox failure when the logging is switched off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/478)

fix(chatform): Remove assertion that breaks friend information call.

---

src/core/coreav.cpp
src/core/coreav.h

In rare cases we can get the deadlock during call cancellation.
1. User hits hang up and the `QWriteLocker locker{&callsLock};` will lock the frame processing
2. Now in very edge case, the frame comes between the (1) and the call `toxav_call_control(toxav.get(), friendNum, TOXAV_CALL_CONTROL_CANCEL, &err);` which will never complete as it will hit the mutex inside toxcore (`ToxAv->mutex`). This mutex will wait for frame to be processed , which will never happen because of (1)
In this PR we stop processing frames as far as used cancelled the call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/489)

fix(video): fix rare deadlock during call cancelation

---

src/video/cameradevice.cpp
src/video/cameradevice.h
src/video/camerasource.cpp

* Use new way of getting device list;
* Remove warning about inability ti select the device when no devices are selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/488)

fix(video): fix the way camera devices are taken, remove warning, when no device is selected

---

themes/dark/statusButton/statusButton.qss
themes/default/statusButton/statusButton.qss

In Qt6 the icon is left aligned by default, so it seems trimmed from the left. Here we explicitly set alignment to centre.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/515)

fix(chatform): fix the status button alignment

---

platform/windows/cross-compile/build.sh
platform/windows/cross-compile/dll-deps

Only libssp isn't needed by ci-tools, because it's a transitive dependency of toxcore (or opus/vpx/sodium, not sure).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/542)

chore: Unify windows builder script with ci-tools.

---

src/video/cameradevice.cpp

`std::array`'s equality is constexpr only in C++20 and later.
Fixes https://github.com/TokTok/qTox/issues/548
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/549)

cleanup: Fix compilation under C++17.

---

.gitignore
CMakePresets.json
src/core/toxpk.cpp
src/persistence/settings.cpp

We parse it as Tox public key, but allow nospam+checksum suffixes.
Also, don't crash when the Tox public key is the wrong size. It'll probably do weird things afterwards, but there seem to be real users with those broken (0-sized) keys in their settings. I'd rather not load them, but the NDEBUG behaviour was to accept them, so we keep them like this for now.
Fixes #562. Fixes #567.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/563)

fix(Startup): Allow Tox Address in the friend address settings.

---

src/chatlog/chatmessage.cpp
src/chatlog/textformatter.cpp
src/chatlog/textformatter.h
src/core/core.cpp
src/core/toxstring.cpp
src/core/toxstring.h
src/model/notificationgenerator.cpp
src/persistence/inotificationsettings.h
src/persistence/settings.cpp
src/persistence/settings.h
src/platform/desktop_notifications/desktopnotify.cpp
src/widget/form/settings/userinterfaceform.cpp
src/widget/form/settings/userinterfaceform.h
src/widget/form/settings/userinterfacesettings.ui
test/chatlog/textformatter_test.cpp
test/core/toxstring_test.cpp
test/model/notificationgenerator_test.cpp

We now remove any suffixes after a double `\0` instead of looking for a specific trifa suffix. This is not ideal, but still less risky than the current implementation.
The current implementation allows anyone (including qTox users) to put text into a `[TRIfA_SUFFIX]text here[/TRIfA_SUFFIX]` message, which could be quite annoying.
Also, this change makes the `hidePostNullSuffix` setting default to false, because this should be an opt-in. TCS requires that we display incoming messages as much like the original as possible, so this default makes sense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/570)

refactor: Make post-null cleanup code less trifa-specific.

---

src/chatlog/chatwidget.cpp

I don't know how these happen, but now at least we don't crash. We should investigate further.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/579)

fix: Don't crash on chat log layout errors.

---

src/core/toxstring.cpp
src/model/exiftransform.cpp

Fixing some compile errors/warnings that came up when cross-compiling to Windows with Qt 6.9.0.
I have also double-checked the exif image rotating and flipping logic in the function that I have touched, as it seemed a bit weird in how asymmetric the operations in the switch-case are -- it looks correct to me.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/qTox/589)

fix: Build failures on Qt 6.9
